
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.github.weichun97.cxf;

import org.springframework.stereotype.Service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.6
 * 2023-11-10T10:26:20.574+08:00
 * Generated source version: 3.5.6
 *
 * 指定beanName,防止和客户端的bean冲突
 */
@Service("serverHelloWorldService")
@javax.jws.WebService(
        serviceName = "MyHelloWorldService",
        portName = "HelloWorldServicePort",
        targetNamespace = "http://cxf.tg.com/",
        wsdlLocation = "file:/D:/work/study/java/test2/webservice-test/src/main/resources/HelloWorldService.wsdl",
        endpointInterface = "com.github.weichun97.cxf.HelloWorldService")

public class HelloWorldServicePortImpl implements HelloWorldService {

    private static final Logger LOG = Logger.getLogger(HelloWorldServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.github.weichun97.cxf.HelloWorldService#sayHello(java.lang.String name)*
     */
    public java.lang.String sayHello(java.lang.String name) {
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            java.lang.String _return = "你好," + name;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.github.weichun97.cxf.HelloWorldService#getPerson(java.lang.String name)*
     */
    public com.github.weichun97.cxf.Person getPerson(java.lang.String name) {
        LOG.info("Executing operation getPerson");
        System.out.println(name);
        try {
            com.github.weichun97.cxf.Person _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
