package com.github.weichun97.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.6
 * 2023-11-10T10:26:20.628+08:00
 * Generated source version: 3.5.6
 *
 */
@WebService(targetNamespace = "http://cxf.tg.com/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://cxf.tg.com/", className = "com.github.weichun97.cxf.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://cxf.tg.com/", className = "com.github.weichun97.cxf.SayHelloResponse")
    @WebResult(name = "returnHello", targetNamespace = "")
    public java.lang.String sayHello(

        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebMethod
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://cxf.tg.com/", className = "com.github.weichun97.cxf.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://cxf.tg.com/", className = "com.github.weichun97.cxf.GetPersonResponse")
    @WebResult(name = "returnPerson", targetNamespace = "")
    public com.github.weichun97.cxf.Person getPerson(

        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
