spring:
  application:
    name: test
  datasource:
    url: jdbc:h2:~/demo;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: root
    password: root
    driverClassName: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
server:
  port: 8100